Update init

diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,96 +1,50 @@
-#!/bin/busybox sh
+#!/bin/bash
 
 mount -t proc none /proc
 mount -t sysfs none /sys
-
-/bin/busybox --install -s 2>/dev/null
 
 # populate /dev
 mknod /dev/tty c 5 0
 
 mdev -s
 
-ROOTDEV="/dev/mmcblk0p2";
-ROOTFSTYPE="ext4";
-ROOTFSOPTS="noatime";
-SPLASH=0;
 RESIZEERROR=0;
 INITIALBOOT=0;
-NORESIZESD="0"
-NOSWAPFILE="0"
-LANMODE="";
-LANADDRESS="";
-LANNETMASK="";
-LANGATEWAY="";
 
-# read cmdline config
-ARRAY=`sed -e '/^#/d' /proc/cmdline | sed -e 's/ /\n/g' | while read line; do
-        if [ ! -z ${line} ]; then
-                if [ $(echo ${line} | grep "=" | wc -l) -eq 1 ]; then
-                        name=${line%%=*};
-			name=${line//./_};
-                        echo ${name}="${line##*=}";
-                else
-			name=${line//./_};
-                        echo ${name}="1";
-                fi
-        fi
-done;`
+declare -A CONFIG;
+CONFIG['rootfstype']="ext4";
+CONFIG['rootfsopts']="noatime";
+CONFIG['root']="/dev/mmcblk0p2";
+CONFIG['splash']=0;
+CONFIG['noresizesd']=0;
+CONFIG['noswapfile']=0;
 
-for line in ${ARRAY}; do
-	case ${line%%=*} in
-		root)
-			ROOTDEV=${line##*=};
-		;;
-		rootfstype)
-			ROOTFSTYPE=${line##*=};
-		;;
-		rootfsopts)
-			ROOTFSOPTS=${line##*=};
-		;;
-		splash)
-			SPLASH=${line##*=}
-		;;
-		noresizesd)
-			NORESIZESD=${line##*=}
-		;;
-		noswapfile)
-			NOSWAPFILE=${line##*=}
-		;;
-		network_eth0_mode)
-			LANMODE=${line##*=}
-		;;
-		network_eth0_netmask)
-			LANNETMASK=${line##*=}
-			LANNETMASK=${LANNETMASK//_/.};
-		;;
-		network_eth0_gateway)
-			LANGATEWAY=${line##*=}
-			LANGATEWAY=${LANGATEWAY//_/.};
-		;;
-		network_eth0_address)
-			LANADDRESS=${line##*=}
-			LANADDRESS=${LANADDRESS//_/.};
-		;;
-	esac
+CMDLINE=($(cat /proc/cmdline));
+for OPTION in ${CMDLINE[@]}; do
+	if [[ $OPTION =~ "=" ]]; then
+		VALUE=$(printf "%b" ${OPTION##*=});
+		CONFIG[${OPTION%%=*}]="$VALUE"
+	else
+		CONFIG[$OPTION]=1;
+	fi
 done
 
 # check if new root partition exists
 X=0;
-while [ ! -b "${ROOTDEV}" ] && [ ${X} -lt 10 ]; do
+while [ ! -b "${CONFIG['root']}" ] && [ ${X} -lt 10 ]; do
 	X=$(($X+1));
 	mdev -s
 	sleep 1;
 done;
 
-if [ ! -b "${ROOTDEV}" ]; then
-	echo "Root partition ${ROOTDEV} missing"
-	exec /bin/busybox sh
+if [ ! -b "${CONFIG['root']}" ]; then
+	echo "Root partition ${CONFIG['root']} missing"
+	exec /bin/bash
 	exit 0
-fi 
+fi
 
 # resize root partition
-if [ "${ROOTDEV}" = "/dev/mmcblk0p2" ] && [ ${NORESIZESD} = "0" ]; then
+if [ "${CONFIG['root']}" == "/dev/mmcblk0p2" ] && [ ${CONFIG['noresizesd']} -eq 0 ]; then
 
 	#Save partition table to file
 	/sbin/sfdisk -d /dev/mmcblk0 > /tmp/curpart.txt
@@ -99,10 +53,10 @@ if [ "${ROOTDEV}" = "/dev/mmcblk0p2" ] && [ ${NORESIZESD} = "0" ]; then
 	cp /tmp/curpart.txt /tmp/part.txt
 
 	#Read partition sizes
-	TOTALBLOCKS=`/sbin/fdisk -l /dev/mmcblk0 | grep total | awk '{printf "%s", $8}'`;
+	TOTALBLOCKS=$(/sbin/fdisk -l /dev/mmcblk0 | grep total | awk '{printf "%s", $8}');
 	LASTBLOCK=$TOTALBLOCKS;
-	PARTSTART=`grep Id=83 /tmp/part.txt | awk '{printf "%d", $4}'`;
-	PARTSIZE=`grep Id=83 /tmp/part.txt | awk '{printf "%d", $6}'`;
+	PARTSTART=$(grep Id=83 /tmp/part.txt | awk '{printf "%d", $4}');
+	PARTSIZE=$(grep Id=83 /tmp/part.txt | awk '{printf "%d", $6}');
 	NEWSIZE=$(($LASTBLOCK-$PARTSTART));
 
 	if [ $PARTSIZE -lt $NEWSIZE ]; then
@@ -116,11 +70,11 @@ if [ "${ROOTDEV}" = "/dev/mmcblk0p2" ] && [ ${NORESIZESD} = "0" ]; then
 		/sbin/sfdisk -d /dev/mmcblk0 > /tmp/newpart.txt
 
 		#Check if the changes could be made to the partition table
-		CHECKSIZE=`grep Id=83 /tmp/newpart.txt | awk '{printf "%d", $6}'`;
+		CHECKSIZE=$(grep Id=83 /tmp/newpart.txt | awk '{printf "%d", $6}');
 
 		if [ $CHECKSIZE -ne $NEWSIZE ]; then
 			#If partition table could not be changed
-			DIFF=`diff /tmp/curpart.txt /tmp/newpart.txt; echo $?`
+			DIFF=$(diff /tmp/curpart.txt /tmp/newpart.txt; echo $?);
 			if [ ${DIFF} != "0" ]; then
 				#Restoring old partition table
 				/sbin/sfdisk --force -q -I /tmp/part.bin /dev/mmcblk0 &> /dev/null
@@ -133,15 +87,15 @@ if [ "${ROOTDEV}" = "/dev/mmcblk0p2" ] && [ ${NORESIZESD} = "0" ]; then
 fi
 
 # mount root partition
-mount -t ${ROOTFSTYPE} -o rw,${ROOTFSOPTS} ${ROOTDEV} /rootfs
+mount -t ${CONFIG['rootfstype']} -o rw,${CONFIG['rootfsopts']} ${CONFIG['root']} /rootfs
 if [ $? -ne 0 ]; then
-	echo "Mounting root partition ${ROOTDEV} failed"
-	exec /bin/busybox sh
+	echo "Mounting root partition ${CONFIG['root']} failed"
+	exec /bin/bash
 	exit 0
 fi
 
 # display splash
-if [ ${SPLASH} = "1" ]; then
+if [ ${CONFIG['splash']} -eq 1 ]; then
 	if [ -f "/rootfs/usr/bin/splash" ]; then
 		if [ -f "/rootfs/var/splash.pid" ]; then
 			rm /rootfs/var/splash.pid;
@@ -156,28 +110,28 @@ fi
 if [ -f /rootfs/root/initialboot ]; then
 	INITIALBOOT=1;
 	rm /rootfs/root/initialboot;
-	if [ ${SPLASH} = "1" ]; then
+	if [ ${CONFIG['splash']} -eq 1 ]; then
 		/rootfs/usr/bin/splash --infinitebar --msgtxt="initial setup...";
 	fi
 fi
 
-if [ "${ROOTDEV}" = "/dev/mmcblk0p2" ] && [ $RESIZEERROR -eq 0 ] && [ ${NORESIZESD} = "0" ]; then
+if [ "${CONFIG['root']}" == "/dev/mmcblk0p2" ] && [ $RESIZEERROR -eq 0 ] && [ ${CONFIG['noresizesd']} -eq 0 ]; then
 	# check if the partition needs resizing
-	FDISKBLOCKSIZE=`/sbin/sfdisk -d /dev/mmcblk0 | grep Id=83 | awk '{printf "%d", $6}'`
-	FDISKBLOCKCOUNT=`/sbin/fdisk -l /dev/mmcblk0 | grep Units | sed -ne 's/\(.*= \)\([0-9]\{1,\}\)\( bytes\)/\2/p'`
-	TUNE2FS=`/sbin/tune2fs -l /dev/mmcblk0p2`
-	TUNEBLOCKSIZE=`echo -e "${TUNE2FS}" | grep "Block size" | awk '{printf "%d", $3}'`
-	TUNEBLOCKCOUNT=`echo -e "${TUNE2FS}" | grep "Block count" | awk '{printf "%d", $3}'`
+	FDISKBLOCKSIZE=$(/sbin/sfdisk -d /dev/mmcblk0 | grep Id=83 | awk '{printf "%d", $6}');
+	FDISKBLOCKCOUNT=$(/sbin/fdisk -l /dev/mmcblk0 | grep Units | sed -ne 's/\(.*= \)\([0-9]\{1,\}\)\( bytes\)/\2/p')
+	TUNE2FS=$(/sbin/tune2fs -l /dev/mmcblk0p2);
+	TUNEBLOCKSIZE=$(echo -e "${TUNE2FS}" | grep "Block size" | awk '{printf "%d", $3}');
+	TUNEBLOCKCOUNT=$(echo -e "${TUNE2FS}" | grep "Block count" | awk '{printf "%d", $3}');
 	TUNETOTALBLOCKS=$(($(($TUNEBLOCKCOUNT*$TUNEBLOCKSIZE))/1024/1024));
 	FDISKTOTALBLOCKS=$(($(($FDISKBLOCKSIZE*$FDISKBLOCKCOUNT))/1024/1024));
-		
+
 	# resize root partition
 	if [ ${TUNETOTALBLOCKS} -lt ${FDISKTOTALBLOCKS} ]; then
-		if [ ${SPLASH} = "1" ]; then
+		if [ ${CONFIG['splash']} -eq 1 ]; then
 			if [ $INITIALBOOT -eq 0 ]; then
 				/rootfs/usr/bin/splash --infinitebar --msgtxt="resizing sd...";
 			fi
-			/rootfs/sbin/resize2fs ${ROOTDEV}
+			/rootfs/sbin/resize2fs ${CONFIG['root']}
 		else
 echo '
 8888888b.  8888888888  .d8888b.  8888888 8888888888P 8888888 888b    888  .d8888b.
@@ -192,93 +146,123 @@ echo '
 		fi
 	fi
 
-	FDISKBLOCKSIZE=`/sbin/sfdisk -d /dev/mmcblk0 | grep Id=83 | awk '{printf "%d", $6}'`
-	FDISKBLOCKCOUNT=`/sbin/fdisk -l /dev/mmcblk0 | grep Units | sed -ne 's/\(.*= \)\([0-9]\{1,\}\)\( bytes\)/\2/p'`
-	TUNE2FS=`/sbin/tune2fs -l /dev/mmcblk0p2`
-	TUNEBLOCKSIZE=`echo -e "${TUNE2FS}" | grep "Block size" | awk '{printf "%d", $3}'`
-	TUNEBLOCKCOUNT=`echo -e "${TUNE2FS}" | grep "Block count" | awk '{printf "%d", $3}'`
+	FDISKBLOCKSIZE=$(/sbin/sfdisk -d /dev/mmcblk0 | grep Id=83 | awk '{printf "%d", $6}');
+	FDISKBLOCKCOUNT=$(/sbin/fdisk -l /dev/mmcblk0 | grep Units | sed -ne 's/\(.*= \)\([0-9]\{1,\}\)\( bytes\)/\2/p');
+	TUNE2FS=$(/sbin/tune2fs -l /dev/mmcblk0p2);
+	TUNEBLOCKSIZE=$(echo -e "${TUNE2FS}" | grep "Block size" | awk '{printf "%d", $3}');
+	TUNEBLOCKCOUNT=$(echo -e "${TUNE2FS}" | grep "Block count" | awk '{printf "%d", $3}');
 	TUNETOTALBLOCKS=$(($(($TUNEBLOCKCOUNT*$TUNEBLOCKSIZE))/1024/1024));
 	FDISKTOTALBLOCKS=$(($(($FDISKBLOCKSIZE*$FDISKBLOCKCOUNT))/1024/1024));
 
 	# check if parition was actually resized
 	if [ ${TUNETOTALBLOCKS} -lt ${FDISKTOTALBLOCKS} ]; then
 		RESIZEERROR=1
-	fi	
+	fi
 fi
 
 # create swapfile
-if [ ! -f /rootfs/var/swapfile ] && [ $RESIZEERROR -eq 0 ] && [ ${NOSWAPFILE} = "0" ]; then
-	if [ ${SPLASH} = "1" ]; then
+if [ ! -f /rootfs/var/swapfile ] && [ $RESIZEERROR -eq 0 ] && [ ${CONFIG['noswapfile']} -eq 0 ]; then
+	if [ ${CONFIG['splash']} -eq 1 ]; then
 		if [ $INITIALBOOT -eq 0 ]; then
 			/rootfs/usr/bin/splash --infinitebar --msgtxt="creating swapfile...";
 		fi
 		dd if=/dev/zero of=/rootfs/var/swapfile bs=1024 count=128000
 	else
 echo '
-       d8888 8888888b.  8888888b.     .d8888b.  888       888        d8888 8888888b.  
-      d88888 888  "Y88b 888  "Y88b   d88P  Y88b 888   o   888       d88888 888   Y88b 
-     d88P888 888    888 888    888   Y88b.      888  d8b  888      d88P888 888    888 
-    d88P 888 888    888 888    888    "Y888b.   888 d888b 888     d88P 888 888   d88P 
-   d88P  888 888    888 888    888       "Y88b. 888d88888b888    d88P  888 8888888P"  
-  d88P   888 888    888 888    888         "888 88888P Y88888   d88P   888 888        
- d8888888888 888  .d88P 888  .d88P   Y88b  d88P 8888P   Y8888  d8888888888 888        
+       d8888 8888888b.  8888888b.     .d8888b.  888       888        d8888 8888888b.
+      d88888 888  "Y88b 888  "Y88b   d88P  Y88b 888   o   888       d88888 888   Y88b
+     d88P888 888    888 888    888   Y88b.      888  d8b  888      d88P888 888    888
+    d88P 888 888    888 888    888    "Y888b.   888 d888b 888     d88P 888 888   d88P
+   d88P  888 888    888 888    888       "Y88b. 888d88888b888    d88P  888 8888888P"
+  d88P   888 888    888 888    888         "888 88888P Y88888   d88P   888 888
+ d8888888888 888  .d88P 888  .d88P   Y88b  d88P 8888P   Y8888  d8888888888 888
 d88P     888 8888888P"  8888888P"     "Y8888P"  888P     Y888 d88P     888 888';
 		dd if=/dev/zero of=/rootfs/var/swapfile bs=1024 count=128000
 	fi
-	/sbin/mkswap /rootfs/var/swapfile &>/dev/null
-	/sbin/swapon /rootfs/var/swapfile &>/dev/null
-	RANSCRIPTS=1;
+	mkswap /rootfs/var/swapfile &>/dev/null
+	swapon /rootfs/var/swapfile &>/dev/null
 fi
 
 # add swapfile to fstab
 if [ -f /rootfs/var/swapfile ]; then
-	IFSWAP=`grep /var/swapfile /rootfs/etc/fstab | wc -l`
-	if [ ${IFSWAP} = "0" ]; then
+	IFSWAP=$(grep /var/swapfile /rootfs/etc/fstab | wc -l);
+	if [ ${IFSWAP} -eq 0 ]; then
 		echo -e '/var/swapfile\tswap\tswap\tdefaults\t0\t0' >> /rootfs/etc/fstab
 	fi
 fi
 
 # continue with normal boot
-if [ ${SPLASH} = "1" ]; then
+if [ ${CONFIG['splash']} -eq 1 ]; then
 	/rootfs/usr/bin/splash --percentagebar --percentage=12 --msgtxt="loading...";
 	# give splash time to settle
 	sleep 1;
 fi
 
-if [ -d /rootfs/lib/modules/`uname -r` ]; then
+if [ -d "/rootfs/lib/modules/$(uname -r)" ]; then
 	# load rpi core module to initialize eth0
-	ln -s /rootfs/lib/modules/`uname -r` /lib/modules/
-	/sbin/modprobe smsc95xx
+	ln -s "/rootfs/lib/modules/$(uname -r)" /lib/modules/
+	ln -s /rootfs/lib/firmware /lib/
+
+	modprobe smsc95xx
 
 	# load additional user kernel modules
 	if [ -f /rootfs/etc/modules ]; then
 		while read MODULE; do
-			if [ ! -z `echo $MODULE | sed -e '/^#/d'` ]; then
-				/sbin/modprobe $MODULE
+			if [ ! -z $(echo $MODULE | sed -e '/^#/d') ]; then
+				modprobe $MODULE
 			fi
 		done < /rootfs/etc/modules
 	fi
+
+	if [ ! -z "${CONFIG['network.wlan0.module']}" ]; then
+		modprobe ${CONFIG['network.wlan0.module']}
+	fi
 	sleep 1;
 
-	# remove eth0 entry in network configuration	
-	awk '/eth0/ {flag=1} /wlan0/{flag=0} !flag{print}' /rootfs/etc/network/interfaces > /rootfs/etc/network/interfaces.new
-	mv /rootfs/etc/network/interfaces.new /rootfs/etc/network/interfaces 
-	if [ "${LANMODE}" = "dhcp" ]; then
-		# connect eth0 to dhcp server
-		echo -e "iface eth0 inet dhcp" >> /rootfs/etc/network/interfaces
+	if [ "${CONFIG['network.wlan0.mode']}" == "dhcp" ] && [ ! -z ${CONFIG['network.wlan0.ssid']} ] && [ ! -z ${CONFIG['network.wlan0.protection']} ]; then
+		# remove wlan0 entry in network configuration
+                awk '/wlan0/ {flag=1} /eth0/{flag=0} !flag{print}' /rootfs/etc/network/interfaces > /rootfs/etc/network/interfaces.new
+		mv /rootfs/etc/network/interfaces.new /rootfs/etc/network/interfaces
 
-		cp /rootfs/etc/network/interfaces /etc/network/
-		/sbin/udhcpc -i eth0 -s /etc/udhcpc/default.script -t 5 -T 5 -b
-	elif [ "${LANMODE}" = "static" ]; then
-		if [ ! -z ${LANADDRESS} ] && [ ! -z ${LANGATEWAY} ] && [ ! -z ${LANNETMASK} ]; then
-			# connect eth0 with an static ip
-			echo -e "iface eth0 inet static\naddress ${LANADDRESS}\nnetmask ${LANNETMASK}\ngateway ${LANGATEWAY}" >> /rootfs/etc/network/interfaces
-			cp /rootfs/etc/network/interfaces /etc/network/
-
-			/sbin/ifconfig eth0 down
-			/sbin/ifconfig eth0 up
-		fi		
+		# connect wlan0 to dhcp server
+		if [ "${CONFIG['network.wlan0.protection']}" == "WPA" ] || [ "${CONFIG['network.wlan0.protection']}" == "WPA2" ]; then
+	                echo -e "allow-hotplug wlan0\niface wlan0 inet dhcp\nwpa-ssid \"${CONFIG['network.wlan0.ssid']}\"\nwpa-psk \"${CONFIG['network.wlan0.password']}\"\n" >> /rootfs/etc/network/interfaces
+			if [ ! -d /rootfs/root/wpa_supplicant ]; then
+				mkdir /rootfs/root/wpa_supplicant;
+			fi
+			echo -e "ctrl_interface=/rootfs/root/wpa_supplicant\nupdate_config=1\nnetwork={\nssid=\"${CONFIG['network.wlan0.ssid']}\"\npsk=\"${CONFIG['network.wlan0.password']}\"\nkey_mgmt=WPA-PSK\nproto=RSN WPA\npairwise=CCMP TKIP\ngroup=CCMP TKIP\n}" > /etc/wpa_supplicant/wpa_supplicant.conf
+			echo -e "ctrl_interface=/root/wpa_supplicant\nupdate_config=1\nnetwork={\nssid=\"${CONFIG['network.wlan0.ssid']}\"\npsk=\"${CONFIG['network.wlan0.password']}\"\nkey_mgmt=WPA-PSK\nproto=RSN WPA\npairwise=CCMP TKIP\ngroup=CCMP TKIP\n}" > /rootfs/etc/wpa_supplicant/wpa_supplicant.conf
+		elif [ "${CONFIG['network.wlan0.protection']}" == "WEP" ]; then
+	                echo -e "allow-hotplug wlan0\niface wlan0 inet dhcp\nwireless-ssid ${CONFIG['network.wlan0.ssid']}\nwireless-key ${CONFIG['network.wlan0.password']}\n" >> /rootfs/etc/network/interfaces
+		elif [ "${CONFIG['network.wlan0.protection']}" == "open" ]; then
+                	echo -e "allow-hotplug wlan0\niface wlan0 inet dhcp\nwireless-ssid ${CONFIG['network.wlan0.protection']}\nwireless-mode managed\n" >> /rootfs/etc/network/interfaces
+		fi
 	fi
+
+	if [ "${CONFIG['network.eth0.mode']}" == "dhcp" ]; then
+		# remove eth0 entry in network configuration
+		awk '/eth0/ {flag=1} /wlan0/{flag=0} !flag{print}' /rootfs/etc/network/interfaces > /rootfs/etc/network/interfaces.new
+		mv /rootfs/etc/network/interfaces.new /rootfs/etc/network/interfaces
+
+		# connect eth0 to dhcp server
+		echo -e "iface eth0 inet dhcp\n" >> /rootfs/etc/network/interfaces
+	elif [ "${CONFIG['network.eth0.mode']}" == "static" ] && [ ! -z ${CONFIG['network.eth0.address']} ] && [ ! -z ${CONFIG['network.eth0.gateway']} ] && [ ! -z ${CONFIG['network.eth0.netmask']} ]; then
+		# remove eth0 entry in network configuration
+		awk '/eth0/ {flag=1} /wlan0/{flag=0} !flag{print}' /rootfs/etc/network/interfaces > /rootfs/etc/network/interfaces.new
+		mv /rootfs/etc/network/interfaces.new /rootfs/etc/network/interfaces
+
+		# connect eth0 with an static ip
+		echo -e "iface eth0 inet static\naddress ${CONFIG['network.eth0.address']}\nnetmask ${CONFIG['network.eth0.netmask']}\ngateway ${CONFIG['network.eth0.gateway']}\n" >> /rootfs/etc/network/interfaces
+	fi
+
+	cp /rootfs/etc/network/interfaces /etc/network/
+
+	if [ "${CONFIG['network.eth0.mode']}" == "dhcp" ]; then
+		udhcpc -i eth0 -s /etc/udhcpc/default.script -t 5 -T 5 -b
+	elif [ "${CONFIG['network.eth0.mode']}" == "static" ] && [ ! -z ${CONFIG['network.eth0.address']} ] && [ ! -z ${CONFIG['network.eth0.gateway']} ] && [ ! -z ${CONFIG['network.eth0.netmask']} ]; then
+		ifconfig eth0 up
+	fi
+
 fi
 
 umount /proc
@@ -287,4 +271,4 @@ umount /sys
 exec switch_root /rootfs /sbin/init
 
 echo "Failed to switch_root, dropping to a shell"
-exec /bin/busybox sh 
+exec /bin/bash
