Switch to Free Space Tree (v2) - Since the 16-page kernel of the Raspberry Pi 5 (linux-image-bcm2712 package)   cannot cope with BTRFS space-cache v1, it is switched to space-cache v2   on the fly at boot time.   see https://wiki.tnonline.net/w/Btrfs/Space_Cache

diff --git a/content/etc/xbian-initramfs/init b/content/etc/xbian-initramfs/init
--- a/content/etc/xbian-initramfs/init
+++ b/content/etc/xbian-initramfs/init
@@ -427,8 +427,10 @@ fi
 # mount root partition
 echo "Mounting root as: mount -t ${CONFIG_rootfstype} -o ${CONFIG_rootfsopts} ${CONFIG_root} $CONFIG_newroot" >&2
 if ! $mount_bin -t ${CONFIG_rootfstype} -o noatime,${CONFIG_rootfsopts} ${CONFIG_root} $CONFIG_newroot; then
-	echo "Mounting root partition ${CONFIG_root} failed" >&2
-	drop_shell "noumount"
+	if [ "$CONFIG_rootfstype" != btrfs ] || ! btrfs check --clear-space-cache v1 ${CONFIG_root} || ! $mount_bin -t ${CONFIG_rootfstype} -o space_cache=v2,noatime,${CONFIG_rootfsopts} ${CONFIG_root} $CONFIG_newroot; then
+		echo "Mounting root partition ${CONFIG_root} failed" >&2
+		drop_shell "noumount"
+	fi
 fi
 up "after mount"
 
