helper scripts updates

diff --git a/content/DEBIAN/postinst b/content/DEBIAN/postinst
--- a/content/DEBIAN/postinst
+++ b/content/DEBIAN/postinst
@@ -1,6 +1,10 @@
 #!/bin/bash
 
+exec 2>/dev/null
+
 if [ $1 == "configure" ]; then
+
+	grep -q FORCEINITRAM /etc/default/xbian-initramfs || echo "FORCEINITRAM=no" >> /etc/default/xbian-initramfs
 
 	dpkg-trigger --no-await trigger-xbian-update-initramfs
 
@@ -27,15 +31,27 @@ if [ $1 == "configure" ]; then
 
         insserv -fr /etc/init.d/triggerhappy &>/dev/null
 
+exec 2>&1
+
 elif [ $1 == "triggered" ]; then
 
-        { mountpoint -q /boot && [ "$(findmnt -o source -n /boot)" = '/dev/mmcblk0p1' ]; } || { umount /boot >/dev/null 2>&1; mount -t vfat /dev/mmcblk0p1 /boot || { echo "CAN'T MOUNT BOOT"; exit 1; }; }
+#        { mountpoint -q /boot && [ "$(findmnt -o source -n /boot)" = '/dev/mmcblk0p1' ]; } || { umount /boot >/dev/null 2>&1; mount -t vfat /dev/mmcblk0p1 /boot || { echo "CAN'T MOUNT BOOT"; exit 1; }; }
+        if ! grep -q 'CuBox-i' /proc/cpuinfo; then
+                mountpoint -q /boot || mount /boot || exit 1
+        fi
         /etc/xbian-initramfs/update-initramfs.sh > /dev/null 2>&1
-        if ! grep -q "initramfs initramfs.gz  0x00a00000" /boot/config.txt; then
+        if ! grep -q "initramfs initramfs.gz  0x0a000000" /boot/config.txt; then
             cat /boot/config.txt | grep -v initramfs > /boot/config.txt.new
-            echo "initramfs initramfs.gz  0x00a00000" > /boot/config.txt
+            echo "initramfs initramfs.gz  0x0a000000" > /boot/config.txt
             cat /boot/config.txt.new >> /boot/config.txt
             rm /boot/config.txt.new
+        fi
+
+        if [ -e /etc/xbian_version ] || grep -q 'rootfstype=btrfs' /boot/cmdline.txt; then
+    	    :
+	else
+            echo " SETTING rootfstype=btrfs in cmdline.txt. This will start filesystem conversion during next reboot. As soon as DPKG and APT processes terminate, reboot your RPI " 
+	    sed -i 's/rootfstype=[a-zA-Z0-9]*/rootfstype=btrfs/' /boot/cmdline.txt
         fi
 
 fi
