general clean up and texting updates

diff --git a/content/DEBIAN/postinst b/content/DEBIAN/postinst
--- a/content/DEBIAN/postinst
+++ b/content/DEBIAN/postinst
@@ -20,6 +20,8 @@ if [ $1 == "configure" ]; then
 		fi
 	fi
 
+        touch /var/run/reboot-required
+
         # echo "---UPDATE LOG---"
         # cat "/home/xbian/xbian-initramfs-update.log"
 
@@ -27,14 +29,14 @@ if [ $1 == "configure" ]; then
 
 elif [ $1 == "triggered" ]; then
 
-        needumount=''
-        mountpoint -q /boot || { needumount=yes; mount /boot || exit 1; }
+        { mountpoint -q /boot && [ "$(findmnt -o source -n /boot)" = '/dev/mmcblk0p1' ]; } || { umount /boot >/dev/null 2>&1; mount -t vfat /dev/mmcblk0p1 /boot || { echo "CAN'T MOUNT BOOT"; exit 1; }; }
         /etc/xbian-initramfs/update-initramfs.sh > /dev/null 2>&1
+        if ! grep -q "initramfs initramfs.gz  0x00a00000" /boot/config.txt; then
         cat /boot/config.txt | grep -v initramfs > /boot/config.txt.new
         echo "initramfs initramfs.gz  0x00a00000" > /boot/config.txt
         cat /boot/config.txt.new >> /boot/config.txt
         rm /boot/config.txt.new
-        [ "$needumount" = "yes" ] && umount /boot 
+        fi
 
 fi
 
